# Generated by Django 3.2.3 on 2021-05-26 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(verbose_name='Время покупки')),
                ('sumBuy', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма покупки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='structureBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.book')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.buy')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounDiscount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Размер скидки')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.buy')),
            ],
        ),
    ]
