# Generated by Django 3.2.3 on 2021-05-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('author', models.CharField(max_length=70, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ageLimit', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('kolPages', models.IntegerField(verbose_name='Количество страниц')),
                ('publishing', models.CharField(max_length=70, verbose_name='Издательство')),
                ('yearPublication', models.DateField(verbose_name='Дата издания')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('bookFile', models.FileField(upload_to='books/', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='NDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentNDS', models.IntegerField(verbose_name='Процент НДС')),
                ('type', models.CharField(max_length=70, verbose_name='Вид ставки')),
                ('priceWithNDS', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена с учетом НДС')),
                ('priceNoNDS', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена без учета НДС')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Catalog.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.book')),
                ('Genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.genre')),
            ],
        ),
    ]
